data_governance:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_SECRET') }}"
      port: 5432
      dbname: postgres
      schema: public
      threads: 1

